name: Waka Readme

on:
  workflow_dispatch:
  schedule:
    - cron: "0 */24 * * *"

jobs:
  update-readme:
    name: Update README
    runs-on: ubuntu-latest
    steps:
      - uses: anmol098/waka-readme-stats@master
        with:
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          # æ ‡ç­¾
          SHOW_TOTAL_CODE_TIME: False
          SHOW_PROFILE_VIEWS: False
          # GitHub æ•°æ®
          SHOW_SHORT_INFO: False
          # æäº¤æ¶ˆæ¯
          COMMIT_MESSAGE: Update Wakapi stats
          # å›¾å½¢
          BLOCKS: "â¬œğŸŸ¨ğŸŸ©"
          # æ—¶é—´èŒƒå›´
          TIME_RANGE: last_30_days
          # æ˜¾ç¤ºæ—¶é—´
          SHOW_TIME: true
          # æäº¤ç»Ÿè®¡
          SHOW_COMMIT: False
          # ä¸€å‘¨æäº¤ç»Ÿè®¡
          SHOW_DAYS_OF_WEEK: False
          # æ“ä½œç³»ç»Ÿ
          SHOW_OS: False
          # é¡¹ç›®
          SHOW_PROJECTS: False
          # æ—¶åŒº
          SHOW_TIMEZONE: False
          # ç¼–è¾‘å™¨
          SHOW_EDITORS: False
          # ä¸»è¦ç¼–å†™
          SHOW_LANGUAGE_PER_REPO: False
          # æ—¶é—´çº¿
          SHOW_LOC_CHART: False
          # æœ«å°¾æ›´æ–°æ—¥æœŸ
          SHOW_UPDATED_DATE: False
          # è¯­è¨€
          LOCALE: en